### ISSUE TITLE
Recommendation: Think about "universal" styles

### ISSUE THREAD

**Issue by melissamcewen** [APoythress/tea_cozy#2]
For CSS I often evaluate the design and ask "what do these elements of the design all share and how can I turn these into a set of simple rules to express that?"

This often means a section in my CSS where I set "base styles" that apply to the whole page like this

```css
/* Universal Styles */

body {
  margin: 0;
  background-color: black;
  font-family: "Helvetica", sans-serif;
  color: seashell;
  font-size: 22px;
  text-align: center;
}

a {
  color: seashell;
}

h2,
h3,
h4 {
  padding: 10px;
  margin: 0;
}

.flex-container {
  display: flex;
  justify-content: center;
  flex-wrap: wrap;
}
```

That .flex-container can used used for multiple parts of the page
```html
    <!-- Store Section -->

    <div id="store">
      <h2>Tea of the Month</h2>
      <h4>What's Steeping at The Tea Cozy?</h4>
      <div class="flex-container items">
        <div class="item">
          <img src="https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-4/img-berryblitz.jpg" />
          <span>Fall Berry Blitz Tea</span>
        </div>
        <div class="item">
          <img src="https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-4/img-spiced-rum.jpg" />
          <span>Spiced Rum Tea</span>
        </div>
        <div class="item">
          <img src="https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-4/img-donut.jpg" />
          <span>Seasonal Donuts</span>
        </div>
        <div class="item">
          <img src="https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-4/img-donut.jpg" />
          <span>Myrtle Ave Tea</span>
        </div>
        <div class="item">
          <img src="https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-4/img-bedford-bizarre.jpg" />
          <span>Bedford Bizarre Tea</span>
        </div>
      </div>
    </div>

    <!-- Locations Section -->

    <div id="locations">
      <h2>Locations</h2>
      <div class="flex-container locations">
        <div class="location">
          <h3>Downtown</h3>
          <p>384 West 4th St</p>
          <p>Suite 108</p>
          <p>Portland, Maine</p>
        </div>
        <div class="location">
          <h3>East Bayside</h3>
          <p>3433 Phisherman's Avenue</p>
          <p>(Northwest Corner)</p>
          <p>Portland, Maine</p>
        </div>
        <div class="location">
          <h3>Oakdale</h3>
          <p>515 Crescent Avenue</p>
          <p>Second Floor</p>
          <p>Portland, Maine</p>
        </div>
      </div>
    </div>

```
